// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```

// import 'firebase_options.dart';
// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjutYO9cACg3xew1EBFxlWX7EnnxRmKc4',
    appId: '1:288372919139:web:0756321b4b3d820502a156',
    messagingSenderId: '288372919139',
    projectId: 'countertest-84123',
    authDomain: 'countertest-84123.firebaseapp.com',
    databaseURL: 'https://countertest-84123-default-rtdb.firebaseio.com',
    storageBucket: 'countertest-84123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm3lh-MSulZbmZrtrbR2YLSLlRDoagJxQ',
    appId: '1:288372919139:android:29693ce02f1efb9102a156',
    messagingSenderId: '288372919139',
    projectId: 'countertest-84123',
    databaseURL: 'https://countertest-84123-default-rtdb.firebaseio.com',
    storageBucket: 'countertest-84123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBol-jQK-GdePqUBnqhQUKGmtlzFQXimrw',
    appId: '1:288372919139:ios:9c1819272234482602a156',
    messagingSenderId: '288372919139',
    projectId: 'countertest-84123',
    databaseURL: 'https://countertest-84123-default-rtdb.firebaseio.com',
    storageBucket: 'countertest-84123.appspot.com',
    iosClientId:
        '288372919139-e1amrcaj7kbf2lf7in9d5ut52bhn91s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterTest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBol-jQK-GdePqUBnqhQUKGmtlzFQXimrw',
    appId: '1:288372919139:ios:dbce78fa8714941b02a156',
    messagingSenderId: '288372919139',
    projectId: 'countertest-84123',
    databaseURL: 'https://countertest-84123-default-rtdb.firebaseio.com',
    storageBucket: 'countertest-84123.appspot.com',
    iosClientId:
        '288372919139-5c54adh8ifjibjcqhmlo7cfjcm87okso.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterTest2.RunnerTests',
  );
}
